const DANH_SACH_GIAY = [
    {
        id: 1,
        name: "Giày Bóng Đá Zocker Winner Energy Gen 2 - Xanh Đen TF",
        brand: "Zocker",
        priceRaw: 800000,
        priceSale: 699000,
        colors: ["Xanh Đen"],
        sizes: [39, 40, 41, 42, 43, 44, 45],
        image: "zocker.jpg",
        images: ["zocker.jpg", "zocker_1.jpg", "zocker_2.jpg", "zocker_3.jpg"],
        desc: "Giày Bóng Đá Zocker Winner Energy Gen 2 Xanh Đen TF sở hữu thiết kế mạnh mẽ, đế TF bám sân tốt cùng form ôm chân thoải mái. Lựa chọn lý tưởng cho các trận đấu sân cỏ nhân tạo với độ ổn định và cảm giác bóng ấn tượng.",
        featured: true
    },
    {
        id: 2,
        name: " Giày Bóng Đá Zocker Winner Energy Gen 2 - Xanh Nhạt TF",
        brand: "Zocker",
        priceRaw: 800000,
        priceSale: 699000,
        colors: ["Xanh Nhạt"],
        sizes: [39, 40, 41, 42, 43, 44, 45],
        image: "zocker1.jpg",
        images: ["zocker1.jpg", "zocker1_1.jpg", "zocker1_2.jpg", "zocker1_3.jpg"],
        desc: "Giày Bóng Đá Zocker Winner Energy Gen 2 Xanh Nhạt TF nổi bật với phối màu trẻ trung, hiện đại cùng thiết kế tối ưu cho sân cỏ nhân tạo. Đế TF bám sân hiệu quả, hỗ trợ di chuyển linh hoạt và kiểm soát bóng tự tin trong mọi pha xử lý.",
        featured: true
    },
    {
        id: 3,
        name: "Giày Bóng Đá Việt Nam Superfly 11 Xanh Chuối Gót Bạc TF",
        brand: "Winbro",
        priceRaw: 420000,
        priceSale: 169000,
        colors: ["Xanh Chuối"],
        sizes: [39, 40, 41, 42, 43, 44, 45],
        image: "fly11.jpg",
        images: ["fly11.jpg", "fly11_1.jpg", "fly11_2.jpg", "fly11_3.jpg"],
        desc: "Giày Bóng Đá Việt Nam Superfly 11 Xanh Chuối Gót Bạc TF gây ấn tượng với phối màu nổi bật, năng động và cá tính. Đế TF bám sân tốt, thân giày ôm chân giúp tăng sự ổn định, hỗ trợ bứt tốc và xử lý bóng hiệu quả trên sân cỏ nhân tạo.",
        featured: true
    },
    {
        id: 4,
        name: "Adidas Predator Accuracy.3 TF - Black & Gold Fusion",
        brand: "Adidas",
        priceRaw: 1100000,
        priceSale: 850000,
        colors: ["Đen"],
        sizes: [39, 41, 42, 43, 44, 45],
        image: "1images.png",
        images: ["1images.png", "adidas-main.jpg", "adidas-side.jpg", "adidas-sole.jpg"],
        desc: "Kiểm soát đường bóng xoáy hoàn hảo với hệ thống vân cao su High Definition Grip. Sự kết hợp tinh tế giữa nền đen và sọc vàng đồng tạo điểm nhấn đẳng cấp trên sân phủi.",
        featured: false
    },
    {
    id: 5,
    name: "Nike Mercurial Vapor 17 - Classic",
    brand: "Nike",
    priceRaw: 1200000,
    priceSale: 950000,
    colors: ["Xanh Chuối"],
    sizes: [39, 40, 41, 42, 43, 44, 45],
    image: "vapor17.jpg",
    images: ["vapor17.jpg", "vapor17_1.jpg", "vapor17_2.jpg", "vapor17_3.jpg"],
    desc: "Dòng Vapor kinh điển với thiết kế năng động...",
    featured: true
    },
    {
    id: 6,
    name: "Dây Kháng Lực",
    brand: "Phụ Kiện",
    priceRaw: 50000,
    priceSale: 30000,
    colors: ["Xanh Lá", "Xanh Dương", "Đỏ", "Đen"],
    sizes: [2_5kg, 5_7kg, 7_10kg, 10_15kg],
    image: "nc.jpg",
    images: ["nc.jpg", "nc.jpg", "nc.jpg", "nc.jpg"],
    desc: "Nếu bạn mới tập hoặc dùng để tập các nhóm cơ nhỏ như vai, tay, ngực, hãy bắt đầu từ sợi nhẹ nhất (từ 2kg - 5kg). Nếu tập các bài thân dưới như Squat, Hip Thrust (mông, đùi), bạn nên chọn các sợi từ mức Trung bình (đỏ/đen - từ 9kg trở lên) thì mới cảm nhận rõ cơ bắp được kích hoạt.",
    featured: true
    },
    {
    id: 7,
    name: "Tất(Vớ)",
    brand: "Phụ Kiện",
    priceRaw: 30000,
    priceSale: 25000,
    colors: ["Trắng", "Đen"],
    sizes: [1],
    image: "nc.jpg",
    images: ["nc.jpg", "nc.jpg", "nc.jpg", "nc.jpg"],
    desc: " bạn đá bóng: Hãy chọn tất có vùng đệm xù dày ở gót và mũi chân để giảm chấn thương, hoặc đầu tư tất chống trượt (loại có các miếng silicone dưới lòng bàn chân) để chân bám chặt vào lót giày, không bị trượt bên trong giày khi chạy.",
    featured: true
    },
    id: 7,
    name: "Bó Gối",
    brand: "Phụ Kiện",
    priceRaw: 300000,
    priceSale: 250000,
    colors: ["Trắng", "Đen"],
    sizes: [M, L],
    image: "nc.jpg",
    images: ["nc.jpg", "nc.jpg", "nc.jpg", "nc.jpg"],
    desc: "Chọn loại phù hợp với mức độ vận động và tình trạng khớp gối của bạn.",
    featured: true
    }
];
